/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppVaultRouteImport } from './routes/_app/vault'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppAdvisorsRouteImport } from './routes/_app/advisors'
import { Route as ApiVaultIndexRouteImport } from './routes/api/vault/index'
import { Route as ApiConversationsIndexRouteImport } from './routes/api/conversations/index'
import { Route as ApiVaultDocumentIdRouteImport } from './routes/api/vault/$documentId'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as ApiPaymentsCreateOrderRouteImport } from './routes/api/payments/create-order'
import { Route as ApiConversationsConversationIdRouteImport } from './routes/api/conversations/$conversationId'
import { Route as ApiAuthVerifyInviteRouteImport } from './routes/api/auth/verify-invite'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthReserveInviteRouteImport } from './routes/api/auth/reserve-invite'
import { Route as ApiAuthOnboardRouteImport } from './routes/api/auth/onboard'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAdminUsageRouteImport } from './routes/api/admin/usage'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminInvitesRouteImport } from './routes/api/admin/invites'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiDocumentsDocumentIdAnalyzeRouteImport } from './routes/api/documents/$documentId/analyze'
import { Route as ApiConversationsConversationIdMessagesRouteImport } from './routes/api/conversations/$conversationId/messages'
import { Route as ApiAdminInvitesInviteIdRouteImport } from './routes/api/admin/invites/$inviteId'
import { Route as ApiAdminWaitlistWaitlistIdDeclineRouteImport } from './routes/api/admin/waitlist/$waitlistId/decline'
import { Route as ApiAdminWaitlistWaitlistIdApproveRouteImport } from './routes/api/admin/waitlist/$waitlistId/approve'
import { Route as ApiAdminMembersMemberIdRevokeRouteImport } from './routes/api/admin/members/$memberId/revoke'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorsRoute = AppAdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => AppRoute,
} as any)
const ApiVaultIndexRoute = ApiVaultIndexRouteImport.update({
  id: '/api/vault/',
  path: '/api/vault/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIndexRoute = ApiConversationsIndexRouteImport.update({
  id: '/api/conversations/',
  path: '/api/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultDocumentIdRoute = ApiVaultDocumentIdRouteImport.update({
  id: '/api/vault/$documentId',
  path: '/api/vault/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCreateOrderRoute = ApiPaymentsCreateOrderRouteImport.update({
  id: '/api/payments/create-order',
  path: '/api/payments/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsConversationIdRoute =
  ApiConversationsConversationIdRouteImport.update({
    id: '/api/conversations/$conversationId',
    path: '/api/conversations/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthVerifyInviteRoute = ApiAuthVerifyInviteRouteImport.update({
  id: '/api/auth/verify-invite',
  path: '/api/auth/verify-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthReserveInviteRoute = ApiAuthReserveInviteRouteImport.update({
  id: '/api/auth/reserve-invite',
  path: '/api/auth/reserve-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOnboardRoute = ApiAuthOnboardRouteImport.update({
  id: '/api/auth/onboard',
  path: '/api/auth/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsageRoute = ApiAdminUsageRouteImport.update({
  id: '/api/admin/usage',
  path: '/api/admin/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInvitesRoute = ApiAdminInvitesRouteImport.update({
  id: '/api/admin/invites',
  path: '/api/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsDocumentIdAnalyzeRoute =
  ApiDocumentsDocumentIdAnalyzeRouteImport.update({
    id: '/api/documents/$documentId/analyze',
    path: '/api/documents/$documentId/analyze',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConversationsConversationIdMessagesRoute =
  ApiConversationsConversationIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)
const ApiAdminInvitesInviteIdRoute = ApiAdminInvitesInviteIdRouteImport.update({
  id: '/$inviteId',
  path: '/$inviteId',
  getParentRoute: () => ApiAdminInvitesRoute,
} as any)
const ApiAdminWaitlistWaitlistIdDeclineRoute =
  ApiAdminWaitlistWaitlistIdDeclineRouteImport.update({
    id: '/api/admin/waitlist/$waitlistId/decline',
    path: '/api/admin/waitlist/$waitlistId/decline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminWaitlistWaitlistIdApproveRoute =
  ApiAdminWaitlistWaitlistIdApproveRouteImport.update({
    id: '/api/admin/waitlist/$waitlistId/approve',
    path: '/api/admin/waitlist/$waitlistId/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminMembersMemberIdRevokeRoute =
  ApiAdminMembersMemberIdRevokeRouteImport.update({
    id: '/api/admin/members/$memberId/revoke',
    path: '/api/admin/members/$memberId/revoke',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/advisors': typeof AppAdvisorsRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/vault': typeof AppVaultRoute
  '/api/chat': typeof ApiChatRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/invites': typeof ApiAdminInvitesRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/usage': typeof ApiAdminUsageRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/onboard': typeof ApiAuthOnboardRoute
  '/api/auth/reserve-invite': typeof ApiAuthReserveInviteRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/verify-invite': typeof ApiAuthVerifyInviteRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/vault/$documentId': typeof ApiVaultDocumentIdRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/vault/': typeof ApiVaultIndexRoute
  '/api/admin/invites/$inviteId': typeof ApiAdminInvitesInviteIdRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
  '/api/documents/$documentId/analyze': typeof ApiDocumentsDocumentIdAnalyzeRoute
  '/api/admin/members/$memberId/revoke': typeof ApiAdminMembersMemberIdRevokeRoute
  '/api/admin/waitlist/$waitlistId/approve': typeof ApiAdminWaitlistWaitlistIdApproveRoute
  '/api/admin/waitlist/$waitlistId/decline': typeof ApiAdminWaitlistWaitlistIdDeclineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/advisors': typeof AppAdvisorsRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/vault': typeof AppVaultRoute
  '/api/chat': typeof ApiChatRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/invites': typeof ApiAdminInvitesRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/usage': typeof ApiAdminUsageRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/onboard': typeof ApiAuthOnboardRoute
  '/api/auth/reserve-invite': typeof ApiAuthReserveInviteRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/verify-invite': typeof ApiAuthVerifyInviteRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/vault/$documentId': typeof ApiVaultDocumentIdRoute
  '/api/conversations': typeof ApiConversationsIndexRoute
  '/api/vault': typeof ApiVaultIndexRoute
  '/api/admin/invites/$inviteId': typeof ApiAdminInvitesInviteIdRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
  '/api/documents/$documentId/analyze': typeof ApiDocumentsDocumentIdAnalyzeRoute
  '/api/admin/members/$memberId/revoke': typeof ApiAdminMembersMemberIdRevokeRoute
  '/api/admin/waitlist/$waitlistId/approve': typeof ApiAdminWaitlistWaitlistIdApproveRoute
  '/api/admin/waitlist/$waitlistId/decline': typeof ApiAdminWaitlistWaitlistIdDeclineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/access': typeof AccessRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/_app/advisors': typeof AppAdvisorsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/vault': typeof AppVaultRoute
  '/api/chat': typeof ApiChatRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/invites': typeof ApiAdminInvitesRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/usage': typeof ApiAdminUsageRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/onboard': typeof ApiAuthOnboardRoute
  '/api/auth/reserve-invite': typeof ApiAuthReserveInviteRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/verify-invite': typeof ApiAuthVerifyInviteRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/payments/create-order': typeof ApiPaymentsCreateOrderRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/vault/$documentId': typeof ApiVaultDocumentIdRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/vault/': typeof ApiVaultIndexRoute
  '/api/admin/invites/$inviteId': typeof ApiAdminInvitesInviteIdRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
  '/api/documents/$documentId/analyze': typeof ApiDocumentsDocumentIdAnalyzeRoute
  '/api/admin/members/$memberId/revoke': typeof ApiAdminMembersMemberIdRevokeRoute
  '/api/admin/waitlist/$waitlistId/approve': typeof ApiAdminWaitlistWaitlistIdApproveRoute
  '/api/admin/waitlist/$waitlistId/decline': typeof ApiAdminWaitlistWaitlistIdDeclineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/admin'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/waitlist'
    | '/advisors'
    | '/chat'
    | '/dashboard'
    | '/vault'
    | '/api/chat'
    | '/api/upload'
    | '/api/waitlist'
    | '/api/admin/dashboard'
    | '/api/admin/invites'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/usage'
    | '/api/auth/forgot-password'
    | '/api/auth/onboard'
    | '/api/auth/reserve-invite'
    | '/api/auth/reset-password'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/verify-invite'
    | '/api/conversations/$conversationId'
    | '/api/payments/create-order'
    | '/api/payments/webhook'
    | '/api/vault/$documentId'
    | '/api/conversations/'
    | '/api/vault/'
    | '/api/admin/invites/$inviteId'
    | '/api/conversations/$conversationId/messages'
    | '/api/documents/$documentId/analyze'
    | '/api/admin/members/$memberId/revoke'
    | '/api/admin/waitlist/$waitlistId/approve'
    | '/api/admin/waitlist/$waitlistId/decline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/admin'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/waitlist'
    | '/advisors'
    | '/chat'
    | '/dashboard'
    | '/vault'
    | '/api/chat'
    | '/api/upload'
    | '/api/waitlist'
    | '/api/admin/dashboard'
    | '/api/admin/invites'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/usage'
    | '/api/auth/forgot-password'
    | '/api/auth/onboard'
    | '/api/auth/reserve-invite'
    | '/api/auth/reset-password'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/verify-invite'
    | '/api/conversations/$conversationId'
    | '/api/payments/create-order'
    | '/api/payments/webhook'
    | '/api/vault/$documentId'
    | '/api/conversations'
    | '/api/vault'
    | '/api/admin/invites/$inviteId'
    | '/api/conversations/$conversationId/messages'
    | '/api/documents/$documentId/analyze'
    | '/api/admin/members/$memberId/revoke'
    | '/api/admin/waitlist/$waitlistId/approve'
    | '/api/admin/waitlist/$waitlistId/decline'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/access'
    | '/admin'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/waitlist'
    | '/_app/advisors'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/vault'
    | '/api/chat'
    | '/api/upload'
    | '/api/waitlist'
    | '/api/admin/dashboard'
    | '/api/admin/invites'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/usage'
    | '/api/auth/forgot-password'
    | '/api/auth/onboard'
    | '/api/auth/reserve-invite'
    | '/api/auth/reset-password'
    | '/api/auth/session'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/verify-invite'
    | '/api/conversations/$conversationId'
    | '/api/payments/create-order'
    | '/api/payments/webhook'
    | '/api/vault/$documentId'
    | '/api/conversations/'
    | '/api/vault/'
    | '/api/admin/invites/$inviteId'
    | '/api/conversations/$conversationId/messages'
    | '/api/documents/$documentId/analyze'
    | '/api/admin/members/$memberId/revoke'
    | '/api/admin/waitlist/$waitlistId/approve'
    | '/api/admin/waitlist/$waitlistId/decline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccessRoute: typeof AccessRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  WaitlistRoute: typeof WaitlistRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminInvitesRoute: typeof ApiAdminInvitesRouteWithChildren
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminUsageRoute: typeof ApiAdminUsageRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthOnboardRoute: typeof ApiAuthOnboardRoute
  ApiAuthReserveInviteRoute: typeof ApiAuthReserveInviteRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiAuthVerifyInviteRoute: typeof ApiAuthVerifyInviteRoute
  ApiConversationsConversationIdRoute: typeof ApiConversationsConversationIdRouteWithChildren
  ApiPaymentsCreateOrderRoute: typeof ApiPaymentsCreateOrderRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  ApiVaultDocumentIdRoute: typeof ApiVaultDocumentIdRoute
  ApiConversationsIndexRoute: typeof ApiConversationsIndexRoute
  ApiVaultIndexRoute: typeof ApiVaultIndexRoute
  ApiDocumentsDocumentIdAnalyzeRoute: typeof ApiDocumentsDocumentIdAnalyzeRoute
  ApiAdminMembersMemberIdRevokeRoute: typeof ApiAdminMembersMemberIdRevokeRoute
  ApiAdminWaitlistWaitlistIdApproveRoute: typeof ApiAdminWaitlistWaitlistIdApproveRoute
  ApiAdminWaitlistWaitlistIdDeclineRoute: typeof ApiAdminWaitlistWaitlistIdDeclineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advisors': {
      id: '/_app/advisors'
      path: '/advisors'
      fullPath: '/advisors'
      preLoaderRoute: typeof AppAdvisorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/vault/': {
      id: '/api/vault/'
      path: '/api/vault'
      fullPath: '/api/vault/'
      preLoaderRoute: typeof ApiVaultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/': {
      id: '/api/conversations/'
      path: '/api/conversations'
      fullPath: '/api/conversations/'
      preLoaderRoute: typeof ApiConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/$documentId': {
      id: '/api/vault/$documentId'
      path: '/api/vault/$documentId'
      fullPath: '/api/vault/$documentId'
      preLoaderRoute: typeof ApiVaultDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/create-order': {
      id: '/api/payments/create-order'
      path: '/api/payments/create-order'
      fullPath: '/api/payments/create-order'
      preLoaderRoute: typeof ApiPaymentsCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$conversationId': {
      id: '/api/conversations/$conversationId'
      path: '/api/conversations/$conversationId'
      fullPath: '/api/conversations/$conversationId'
      preLoaderRoute: typeof ApiConversationsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-invite': {
      id: '/api/auth/verify-invite'
      path: '/api/auth/verify-invite'
      fullPath: '/api/auth/verify-invite'
      preLoaderRoute: typeof ApiAuthVerifyInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reserve-invite': {
      id: '/api/auth/reserve-invite'
      path: '/api/auth/reserve-invite'
      fullPath: '/api/auth/reserve-invite'
      preLoaderRoute: typeof ApiAuthReserveInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/onboard': {
      id: '/api/auth/onboard'
      path: '/api/auth/onboard'
      fullPath: '/api/auth/onboard'
      preLoaderRoute: typeof ApiAuthOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/usage': {
      id: '/api/admin/usage'
      path: '/api/admin/usage'
      fullPath: '/api/admin/usage'
      preLoaderRoute: typeof ApiAdminUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/invites': {
      id: '/api/admin/invites'
      path: '/api/admin/invites'
      fullPath: '/api/admin/invites'
      preLoaderRoute: typeof ApiAdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$documentId/analyze': {
      id: '/api/documents/$documentId/analyze'
      path: '/api/documents/$documentId/analyze'
      fullPath: '/api/documents/$documentId/analyze'
      preLoaderRoute: typeof ApiDocumentsDocumentIdAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$conversationId/messages': {
      id: '/api/conversations/$conversationId/messages'
      path: '/messages'
      fullPath: '/api/conversations/$conversationId/messages'
      preLoaderRoute: typeof ApiConversationsConversationIdMessagesRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
    '/api/admin/invites/$inviteId': {
      id: '/api/admin/invites/$inviteId'
      path: '/$inviteId'
      fullPath: '/api/admin/invites/$inviteId'
      preLoaderRoute: typeof ApiAdminInvitesInviteIdRouteImport
      parentRoute: typeof ApiAdminInvitesRoute
    }
    '/api/admin/waitlist/$waitlistId/decline': {
      id: '/api/admin/waitlist/$waitlistId/decline'
      path: '/api/admin/waitlist/$waitlistId/decline'
      fullPath: '/api/admin/waitlist/$waitlistId/decline'
      preLoaderRoute: typeof ApiAdminWaitlistWaitlistIdDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/waitlist/$waitlistId/approve': {
      id: '/api/admin/waitlist/$waitlistId/approve'
      path: '/api/admin/waitlist/$waitlistId/approve'
      fullPath: '/api/admin/waitlist/$waitlistId/approve'
      preLoaderRoute: typeof ApiAdminWaitlistWaitlistIdApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/members/$memberId/revoke': {
      id: '/api/admin/members/$memberId/revoke'
      path: '/api/admin/members/$memberId/revoke'
      fullPath: '/api/admin/members/$memberId/revoke'
      preLoaderRoute: typeof ApiAdminMembersMemberIdRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdvisorsRoute: typeof AppAdvisorsRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppVaultRoute: typeof AppVaultRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorsRoute: AppAdvisorsRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppVaultRoute: AppVaultRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAdminInvitesRouteChildren {
  ApiAdminInvitesInviteIdRoute: typeof ApiAdminInvitesInviteIdRoute
}

const ApiAdminInvitesRouteChildren: ApiAdminInvitesRouteChildren = {
  ApiAdminInvitesInviteIdRoute: ApiAdminInvitesInviteIdRoute,
}

const ApiAdminInvitesRouteWithChildren = ApiAdminInvitesRoute._addFileChildren(
  ApiAdminInvitesRouteChildren,
)

interface ApiConversationsConversationIdRouteChildren {
  ApiConversationsConversationIdMessagesRoute: typeof ApiConversationsConversationIdMessagesRoute
}

const ApiConversationsConversationIdRouteChildren: ApiConversationsConversationIdRouteChildren =
  {
    ApiConversationsConversationIdMessagesRoute:
      ApiConversationsConversationIdMessagesRoute,
  }

const ApiConversationsConversationIdRouteWithChildren =
  ApiConversationsConversationIdRoute._addFileChildren(
    ApiConversationsConversationIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccessRoute: AccessRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  WaitlistRoute: WaitlistRoute,
  ApiChatRoute: ApiChatRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminInvitesRoute: ApiAdminInvitesRouteWithChildren,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminUsageRoute: ApiAdminUsageRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthOnboardRoute: ApiAuthOnboardRoute,
  ApiAuthReserveInviteRoute: ApiAuthReserveInviteRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiAuthVerifyInviteRoute: ApiAuthVerifyInviteRoute,
  ApiConversationsConversationIdRoute:
    ApiConversationsConversationIdRouteWithChildren,
  ApiPaymentsCreateOrderRoute: ApiPaymentsCreateOrderRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  ApiVaultDocumentIdRoute: ApiVaultDocumentIdRoute,
  ApiConversationsIndexRoute: ApiConversationsIndexRoute,
  ApiVaultIndexRoute: ApiVaultIndexRoute,
  ApiDocumentsDocumentIdAnalyzeRoute: ApiDocumentsDocumentIdAnalyzeRoute,
  ApiAdminMembersMemberIdRevokeRoute: ApiAdminMembersMemberIdRevokeRoute,
  ApiAdminWaitlistWaitlistIdApproveRoute:
    ApiAdminWaitlistWaitlistIdApproveRoute,
  ApiAdminWaitlistWaitlistIdDeclineRoute:
    ApiAdminWaitlistWaitlistIdDeclineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
